import 'game_model.dart';

class CampaignChapter {
  final int number; // 1–100
  final String title;
  final String flavorText;
  final int botRating;
  final TimeControl timeControl;

  const CampaignChapter({
    required this.number,
    required this.title,
    required this.flavorText,
    required this.botRating,
    required this.timeControl,
  });

  bool isUnlocked(int progress) => number <= progress + 1;
  bool isCompleted(int progress) => number <= progress;

  static int botRatingForChapter(int chapter) {
    if (chapter <= 10) {
      return 200 + ((chapter - 1) * 33);
    } else if (chapter <= 25) {
      return 500 + ((chapter - 11) * 26);
    } else if (chapter <= 50) {
      return 900 + ((chapter - 26) * 20);
    } else if (chapter <= 75) {
      return 1400 + ((chapter - 51) * 24);
    } else {
      return 2000 + ((chapter - 76) * 40);
    }
  }

  static TimeControl timeControlForChapter(int chapter) {
    if (chapter <= 20) return TimeControls.rapid30;
    if (chapter <= 40) return TimeControls.rapid15plus10;
    if (chapter <= 60) return TimeControls.blitz5;
    if (chapter <= 80) return TimeControls.blitz3;
    return TimeControls.bullet2plus1;
  }

  static final List<CampaignChapter> all = List.generate(100, (i) {
    final n = i + 1;
    return CampaignChapter(
      number: n,
      title: _titles[i],
      flavorText: _flavorTexts[i],
      botRating: botRatingForChapter(n),
      timeControl: timeControlForChapter(n),
    );
  });

  static const _titles = [
    'Chapter 1: First Steps',
    'Chapter 2: Pawn Power',
    'Chapter 3: The Knight\'s Path',
    'Chapter 4: Bishop\'s Diagonal',
    'Chapter 5: Rook and Roll',
    'Chapter 6: The Queen Awakens',
    'Chapter 7: Royal Safety',
    'Chapter 8: The Exchange',
    'Chapter 9: Opening Principles',
    'Chapter 10: The Middle Game',
    'Chapter 11: Pins and Skewers',
    'Chapter 12: Forks',
    'Chapter 13: Discovered Attacks',
    'Chapter 14: The Back Rank',
    'Chapter 15: Zugzwang',
    'Chapter 16: Endgame Basics',
    'Chapter 17: King and Pawn',
    'Chapter 18: Rook Endgames',
    'Chapter 19: The Outpost',
    'Chapter 20: Pawn Structures',
    'Chapter 21: Isolated Pawns',
    'Chapter 22: Passed Pawns',
    'Chapter 23: The Minority Attack',
    'Chapter 24: Weak Squares',
    'Chapter 25: Open Files',
    'Chapter 26: The Sicilian',
    'Chapter 27: French Defense',
    'Chapter 28: Caro-Kann',
    'Chapter 29: King\'s Indian',
    'Chapter 30: Queen\'s Gambit',
    'Chapter 31: The Initiative',
    'Chapter 32: Sacrifices',
    'Chapter 33: Attack on the King',
    'Chapter 34: Defensive Play',
    'Chapter 35: Counterplay',
    'Chapter 36: Piece Coordination',
    'Chapter 37: Space Advantage',
    'Chapter 38: The Minority',
    'Chapter 39: Prophylaxis',
    'Chapter 40: Calculation',
    'Chapter 41: The Ruy Lopez',
    'Chapter 42: The Italian Game',
    'Chapter 43: Nimzowitsch Defense',
    'Chapter 44: The Grünfeld',
    'Chapter 45: The Benoni',
    'Chapter 46: The Dutch',
    'Chapter 47: English Opening',
    'Chapter 48: Réti Opening',
    'Chapter 49: The Bird',
    'Chapter 50: The Halfway Point',
    'Chapter 51: Positional Mastery',
    'Chapter 52: Tactical Vision',
    'Chapter 53: The Endgame Art',
    'Chapter 54: Strategic Plans',
    'Chapter 55: Dynamic Play',
    'Chapter 56: Imbalances',
    'Chapter 57: Opposite Castling',
    'Chapter 58: Closed Positions',
    'Chapter 59: Open Games',
    'Chapter 60: Pawn Majorities',
    'Chapter 61: The Breakthrough',
    'Chapter 62: Rook Activity',
    'Chapter 63: Bishop vs Knight',
    'Chapter 64: Two Bishops',
    'Chapter 65: Knight Outposts',
    'Chapter 66: Rook Behind Passed',
    'Chapter 67: The Lucena',
    'Chapter 68: The Philidor',
    'Chapter 69: Complex Endgames',
    'Chapter 70: The Exchange Sac',
    'Chapter 71: Deep Calculation',
    'Chapter 72: Endgame Technique',
    'Chapter 73: The Windmill',
    'Chapter 74: The Immortal',
    'Chapter 75: Advanced Tactics',
    'Chapter 76: Grandmaster Plans',
    'Chapter 77: The Zugzwang Web',
    'Chapter 78: Fortress Theory',
    'Chapter 79: Interference',
    'Chapter 80: The Clearance',
    'Chapter 81: Deflection',
    'Chapter 82: Decoy Tactics',
    'Chapter 83: The Greek Gift',
    'Chapter 84: Bxh7+ Themes',
    'Chapter 85: The Brilliancy',
    'Chapter 86: Mating Nets',
    'Chapter 87: The Quiet Move',
    'Chapter 88: Zwischenzug',
    'Chapter 89: The Desperado',
    'Chapter 90: Mutual Zugzwang',
    'Chapter 91: Domination',
    'Chapter 92: The Squeeze',
    'Chapter 93: Opposite Bishops',
    'Chapter 94: The Fortress',
    'Chapter 95: Rook vs Pawns',
    'Chapter 96: The Seven Pawns',
    'Chapter 97: Almost There',
    'Chapter 98: The Penultimate',
    'Chapter 99: The Final Trial',
    'Chapter 100: Champion\'s Crown',
  ];

  static const _flavorTexts = [
    'Every grandmaster was once a beginner. Your journey starts here.',
    'The humble pawn holds the power to become a queen. Learn its secrets.',
    'The knight leaps where others dare not tread. Master its unusual path.',
    'Long diagonals hold great power. Let your bishop speak.',
    'Control the open files and you control the board.',
    'The queen is your most powerful weapon. Use her wisely.',
    'A king exposed is a king in danger. Learn to castle safely.',
    'Sometimes you must give to gain. The art of the exchange.',
    'The first ten moves shape the entire game. Choose them well.',
    'The middle game is where battles are won and lost.',
    'A pinned piece cannot defend. Learn to freeze your opponent.',
    'One piece attacking two. The fork is chess at its most efficient.',
    'Reveal a hidden attacker. The discovered attack strikes from the shadows.',
    'The back rank holds a terrible secret for the careless king.',
    'A position where every move worsens your situation. Pure torture.',
    'When pawns and kings dance alone, precision is everything.',
    'The king becomes a warrior in the endgame. Lead from the front.',
    'Rooks belong on open files and behind passed pawns.',
    'A knight planted deep in enemy territory can be unstoppable.',
    'Pawn structure is the skeleton of strategy.',
    'An isolated pawn — weakness or dynamic resource?',
    'A passed pawn dreams only of promotion. Help it reach its destiny.',
    'Attack on one wing to create weakness on the other.',
    'Weak squares cannot be defended by pawns alone.',
    'Open files are highways for your rooks. Clear them.',
    'The Sicilian — a fighting defense that unbalances from move one.',
    'The French — solid, strategic, and patient as stone.',
    'The Caro-Kann — solid structure, clear plans, lasting pressure.',
    'The King\'s Indian — let them advance, then strike back fiercely.',
    'The Queen\'s Gambit — a classical battle for the center.',
    'The initiative is worth more than a pawn. Keep the pressure.',
    'A sacrifice that cannot be refused changes everything.',
    'When you attack the king, there is no going back.',
    'The art of defense is as beautiful as attack.',
    'Even in inferior positions, counterplay can save the day.',
    'Pieces that work together are worth more than their sum.',
    'Space gives your pieces freedom. Restrict your opponent.',
    'Three pawns against four on the queenside. A subtle battle.',
    'The prophylactic move prevents before it threatens.',
    'Count the moves. See the variations. Then decide.',
    'The oldest opening, tested over centuries. Still deadly.',
    'Simple development, clever ideas. The Italian way.',
    'Hypermodern chess — control the center from afar.',
    'A defense that aims for dynamic counterplay against d4.',
    'Give up the center to attack it later. Benoni\'s gamble.',
    'The Dutch fights for e4 with f5. Aggressive from the start.',
    'Control with flanks, not pawns. The English way.',
    'Develop flexibly and fight for key squares. Réti\'s vision.',
    'An unusual opening with surprising bite.',
    'You have reached the midpoint. The hardest half lies ahead.',
    'The master sees the whole board, not just the pieces.',
    'Patterns emerge through study. Trust your tactical vision.',
    'Endgames are chess distilled to its purest form.',
    'Every position has a plan. Find it before your opponent does.',
    'Statics and dynamics in perfect tension.',
    'Every imbalance is an opportunity if you understand it.',
    'When kings castle on opposite sides, the race begins.',
    'In closed positions, maneuvering is everything.',
    'Open games demand concrete calculation above all.',
    'A pawn majority on one side creates an unstoppable force.',
    'The breakthrough pawn shatters the enemy\'s fortress.',
    'An active rook can single-handedly win an endgame.',
    'The eternal question: bishop or knight?',
    'Two bishops of different colors sweep the whole board.',
    'A knight on the sixth rank is like a thorn in the flesh.',
    'Place your rook behind the passed pawn — on your own or theirs.',
    'The Lucena position: the winning technique with rook and pawn.',
    'The Philidor position: the key drawing technique for the defender.',
    'When multiple endgame themes collide, only the precise survive.',
    'Give up the exchange for lasting positional compensation.',
    'Some positions require you to see twelve moves ahead.',
    'Technical precision in the endgame separates masters from amateurs.',
    'The king swings back and forth, cutting off the enemy piece.',
    'One of the most famous games ever played. What can you learn?',
    'Advanced combinations that defy simple categorization.',
    'Your opponent is an engine. Can human creativity defeat silicon?',
    'Every tempo matters when zugzwang looms.',
    'A fortress is a prison — for your opponent\'s winning ambitions.',
    'One piece steps aside so another can deliver the blow.',
    'Clear the path. The clearance sacrifice opens new lines.',
    'Lure the enemy piece to a fatal square.',
    'Tempt the king into a mating net with a decoy sacrifice.',
    'The bishop sacrifice on h7 — a classical attacking weapon.',
    'Bxh7+ followed by Ng5+ — recognize the pattern.',
    'A combination so beautiful it defies practical logic.',
    'Weave a net of attacked squares around the enemy king.',
    'The quiet move — no check, no capture, total domination.',
    'The in-between move that disrupts your opponent\'s plans.',
    'A piece that cannot escape, so it sacrifices itself with purpose.',
    'Both sides run out of useful moves at the same time.',
    'One piece controls another, reducing it to helplessness.',
    'Slowly restrict your opponent until they suffocate.',
    'Opposite-colored bishops create fortress-like draws — or winning attacks.',
    'Build an impregnable position and dare your opponent to break it.',
    'A rook battling alone against a swarm of advancing pawns.',
    'Seven passed pawns and a desperate race. Incredible.',
    'One more victory separates you from the pinnacle.',
    'The penultimate challenge. Compose yourself.',
    'The final test before greatness. Everything you know will be needed.',
    'You have mastered chess. Now claim your crown.',
  ];
}
